### ISSUE TITLE
python_libs test failing on MS Windows

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#112]
With Python 2.7.3 on MS Windows 7, I got this error in testing:

~~~
test\test.py::test_python_libs FAILED
test\test.py::test_python_libs_custom FAILED

================================== FAILURES ===================================
______________________________ test_python_libs _______________________________

    def test_python_libs():
>       configure_build_and_exe('python_libs', 'python setup.py --cxx=g++')

..\..\test.py:229:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\test.py:112: in configure_build_and_exe
    stdout, stderr = exe(binary)
..\..\test.py:69: in exe
    universal_newlines=True).communicate()
C:\Python27\lib\subprocess.py:679: in __init__
    errread, errwrite)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x0231CCD0>, args = 'bin\\example.exe'
executable = None, preexec_fn = None, close_fds = False, cwd = None, env = None
universal_newlines = True
startupinfo = <subprocess.STARTUPINFO instance at 0x023FF328>, creationflags = 0
shell = False, p2cread = <_subprocess_handle object at 0x01E03570>
p2cwrite = None, c2pread = <_subprocess_handle object at 0x01E03580>
c2pwrite = <_subprocess_handle object at 0x01E034C0>
errread = <_subprocess_handle object at 0x01E034E0>
errwrite = <_subprocess_handle object at 0x01E03480>

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       cwd, env, universal_newlines,
                       startupinfo, creationflags, shell,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite):
        """Execute program (MS Windows version)"""

        if not isinstance(args, types.StringTypes):
            args = list2cmdline(args)

        # Process startup details
        if startupinfo is None:
            startupinfo = STARTUPINFO()
        if None not in (p2cread, c2pwrite, errwrite):
            startupinfo.dwFlags |= _subprocess.STARTF_USESTDHANDLES
            startupinfo.hStdInput = p2cread
            startupinfo.hStdOutput = c2pwrite
            startupinfo.hStdError = errwrite

        if shell:
            startupinfo.dwFlags |= _subprocess.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = _subprocess.SW_HIDE
            comspec = os.environ.get("COMSPEC", "cmd.exe")
            args = '{} /c "{}"'.format (comspec, args)
            if (_subprocess.GetVersion() >= 0x80000000 or
                    os.path.basename(comspec).lower() == "command.com"):
                # Win9x, or using command.com on NT. We need to
                # use the w9xpopen intermediate program. For more
                # information, see KB Q150956
                # (http://web.archive.org/web/20011105084002/http://support.microsoft.com/support/kb/articles/Q150/9/56.asp)
                w9xpopen = self._find_w9xpopen()
                args = '"%s" %s' % (w9xpopen, args)
                # Not passing CREATE_NEW_CONSOLE has been known to
                # cause random failures on win9x.  Specifically a
                # dialog: "Your program accessed mem currently in
                # use at xxx" and a hopeful warning about the
                # stability of your system.  Cost is Ctrl+C wont
                # kill children.
                creationflags |= _subprocess.CREATE_NEW_CONSOLE

        # Start the process
        try:
            hp, ht, pid, tid = _subprocess.CreateProcess(executable, args,
                                     # no special security
                                     None, None,
                                     int(not close_fds),
                                     creationflags,
                                     env,
                                     cwd,
>                                    startupinfo)
E                                    WindowsError: [Error 2] SystÚm nem˘×e nßjsŁ zadanř s˙bor

C:\Python27\lib\subprocess.py:896: WindowsError
---------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

TypeError: expected a character buffer object

mingw32-make[2]: *** No rule to make target 'C:/Windows/System32/python27.dll', needed by 'bin/example.exe'.  Stop.
mingw32-make[1]: *** [src/CMakeFiles/example.dir/all] Error 2
mingw32-make: *** [all] Error 2
___________________________ test_python_libs_custom ___________________________

    def test_python_libs_custom():
        setup = 'python setup.py --cxx=g++ --python=%s' % sys.executable
>       configure_build_and_exe('python_libs_custom', setup)

..\..\test.py:234:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\test.py:112: in configure_build_and_exe
    stdout, stderr = exe(binary)
..\..\test.py:69: in exe
    universal_newlines=True).communicate()
C:\Python27\lib\subprocess.py:679: in __init__
    errread, errwrite)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0x0231C0D0>, args = 'bin\\example.exe'
executable = None, preexec_fn = None, close_fds = False, cwd = None, env = None
universal_newlines = True
startupinfo = <subprocess.STARTUPINFO instance at 0x0237F7B0>, creationflags = 0
shell = False, p2cread = <_subprocess_handle object at 0x01E034B0>
p2cwrite = None, c2pread = <_subprocess_handle object at 0x01E03460>
c2pwrite = <_subprocess_handle object at 0x01E03450>
errread = <_subprocess_handle object at 0x01E03470>
errwrite = <_subprocess_handle object at 0x01E034F0>

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       cwd, env, universal_newlines,
                       startupinfo, creationflags, shell,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite):
        """Execute program (MS Windows version)"""

        if not isinstance(args, types.StringTypes):
            args = list2cmdline(args)

        # Process startup details
        if startupinfo is None:
            startupinfo = STARTUPINFO()
        if None not in (p2cread, c2pwrite, errwrite):
            startupinfo.dwFlags |= _subprocess.STARTF_USESTDHANDLES
            startupinfo.hStdInput = p2cread
            startupinfo.hStdOutput = c2pwrite
            startupinfo.hStdError = errwrite

        if shell:
            startupinfo.dwFlags |= _subprocess.STARTF_USESHOWWINDOW
            startupinfo.wShowWindow = _subprocess.SW_HIDE
            comspec = os.environ.get("COMSPEC", "cmd.exe")
            args = '{} /c "{}"'.format (comspec, args)
            if (_subprocess.GetVersion() >= 0x80000000 or
                    os.path.basename(comspec).lower() == "command.com"):
                # Win9x, or using command.com on NT. We need to
                # use the w9xpopen intermediate program. For more
                # information, see KB Q150956
                # (http://web.archive.org/web/20011105084002/http://support.microsoft.com/support/kb/articles/Q150/9/56.asp)
                w9xpopen = self._find_w9xpopen()
                args = '"%s" %s' % (w9xpopen, args)
                # Not passing CREATE_NEW_CONSOLE has been known to
                # cause random failures on win9x.  Specifically a
                # dialog: "Your program accessed mem currently in
                # use at xxx" and a hopeful warning about the
                # stability of your system.  Cost is Ctrl+C wont
                # kill children.
                creationflags |= _subprocess.CREATE_NEW_CONSOLE

        # Start the process
        try:
            hp, ht, pid, tid = _subprocess.CreateProcess(executable, args,
                                     # no special security
                                     None, None,
                                     int(not close_fds),
                                     creationflags,
                                     env,
                                     cwd,
>                                    startupinfo)
E                                    WindowsError: [Error 2] SystÚm nem˘×e nßjsŁ zadanř s˙bor

C:\Python27\lib\subprocess.py:896: WindowsError
---------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

TypeError: expected a character buffer object

mingw32-make[2]: *** No rule to make target 'C:/Windows/System32/python27.dll', needed by 'bin/example.exe'.  Stop.
mingw32-make[1]: *** [src/CMakeFiles/example.dir/all] Error 2
mingw32-make: *** [all] Error 2
============== 2 failed, 19 passed, 2 skipped in 358.60 seconds ===============

C:\Users\dv6-2145ec\Documents\MiroIlias_osobne\dirac_software\autocmake-devel\autocmake_miroi>
~~~

**Comment by miroi** [comment]
Ah, I see problem with MS Windows library identification in python_libs.cmale"
~~~
>>> from distutils.sysconfig import get_config_var; import sys; sys.stdout.write(get_config_var('LIBDIR'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected a character buffer object
~~~
Working on it ...

**Comment by miroi** [comment]
Hi @bast 

On Windows I set this variable below in python_libs.cmake, but *find_library(PYTHON_LIBRARY...* does not find any library in these valid paths:
 
~~~  _PYTHON_LIB_PATH=C:\Windows\SYSTEM32\python27.zip;C:\Python27\DLLs;C:\Python27\lib;C:\Python27\lib\plat-win;C:\Python27\lib\lib-tk;C:\Python27;C:\Python27\lib\site-packages
~~~

What NAMES could be missing ?

**Comment by bast** [comment]
Sorry I have no idea how and where these files are placed on Windows.
