### ISSUE TITLE
IBM Linux: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by miroi** [scisoft/autocmake#38]
On the "Linux login 3.0.76-0.11-ppc64 #1 SMP Fri Jun 14 08:21:43 UTC 2013 (ccab990) ppc64 ppc64 ppc64 GNU/Linux" , what is IBM machine with Linux system, there is something wrong with the connection (see below).

I am opening issue for that as we want to have autocmake running on all platforms, including IBM.

~~~
ilias@147.213.242.7:~/work/programming/autocmake_devel/autocmake/.py.test -v test/test.py 
========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.9 -- py-1.4.30 -- pytest-2.7.2 -- /gpfs/home/utils/LINUX/python-2.7.9/bin/python
rootdir: /gpfs/home/ilias/work/programming/autocmake_devel/autocmake/test, inifile: 
collected 4 items 

test/test.py::test_cxx FAILED
test/test.py::test_cxx_auto FAILED
test/test.py::test_fc FAILED
test/test.py::test_fc_blas FAILED

================================================================ FAILURES ================================================================
________________________________________________________________ test_cxx ________________________________________________________________

    def test_cxx():
>       stdout, stderr = configure_build_and_exe('cxx', 'python setup.py --cxx=g++')

../../test.py:111: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../test.py:85: in configure_build_and_exe
    dst='lib/docopt.py')
../../test.py:45: in fetch_url
    opener.retrieve(src, dst)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:245: in retrieve
    fp = self.open(url, data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:213: in open
    return getattr(self, name)(url)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:443: in open_https
    h.endheaders(data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:997: in endheaders
    self._send_output(message_body)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:850: in _send_output
    self.send(msg)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:812: in send
    self.connect()
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:1212: in connect
    server_hostname=server_hostname)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:350: in wrap_socket
    _context=self)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:566: in __init__
    self.do_handshake()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0xfffae348758>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:788: IOError
_____________________________________________________________ test_cxx_auto ______________________________________________________________

    def test_cxx_auto():
>       stdout, stderr = configure_build_and_exe('cxx_auto', 'python setup.py --cxx=g++')

../../test.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../test.py:85: in configure_build_and_exe
    dst='lib/docopt.py')
../../test.py:45: in fetch_url
    opener.retrieve(src, dst)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:245: in retrieve
    fp = self.open(url, data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:213: in open
    return getattr(self, name)(url)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:443: in open_https
    h.endheaders(data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:997: in endheaders
    self._send_output(message_body)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:850: in _send_output
    self.send(msg)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:812: in send
    self.connect()
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:1212: in connect
    server_hostname=server_hostname)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:350: in wrap_socket
    _context=self)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:566: in __init__
    self.do_handshake()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0xfffae0edc08>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:788: IOError
________________________________________________________________ test_fc _________________________________________________________________

    def test_fc():
>       stdout, stderr = configure_build_and_exe('fc', 'python setup.py --fc=gfortran')

../../test.py:125: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../test.py:85: in configure_build_and_exe
    dst='lib/docopt.py')
../../test.py:45: in fetch_url
    opener.retrieve(src, dst)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:245: in retrieve
    fp = self.open(url, data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:213: in open
    return getattr(self, name)(url)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:443: in open_https
    h.endheaders(data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:997: in endheaders
    self._send_output(message_body)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:850: in _send_output
    self.send(msg)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:812: in send
    self.connect()
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:1212: in connect
    server_hostname=server_hostname)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:350: in wrap_socket
    _context=self)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:566: in __init__
    self.do_handshake()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0xfffae0edde8>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:788: IOError
______________________________________________________________ test_fc_blas ______________________________________________________________

    def test_fc_blas():
        if sys.platform != 'win32':
>           stdout, stderr = configure_build_and_exe('fc_blas', 'python setup.py --fc=gfortran --blas=auto')

../../test.py:133: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../test.py:85: in configure_build_and_exe
    dst='lib/docopt.py')
../../test.py:45: in fetch_url
    opener.retrieve(src, dst)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:245: in retrieve
    fp = self.open(url, data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:213: in open
    return getattr(self, name)(url)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py:443: in open_https
    h.endheaders(data)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:997: in endheaders
    self._send_output(message_body)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:850: in _send_output
    self.send(msg)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:812: in send
    self.connect()
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py:1212: in connect
    server_hostname=server_hostname)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:350: in wrap_socket
    _context=self)
/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:566: in __init__
    self.do_handshake()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ssl.SSLSocket object at 0xfffae0edd70>, block = False

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
>           self._sslobj.do_handshake()
E           IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:788: IOError
======================================================== 4 failed in 2.71 seconds ========================================================
ilias@147.213.242.7:~/work/programming/autocmake_devel/autocmake/.
~~~

**Comment by bast** [comment]
And you can correctly clone Autocmake on that machine over HTTPS?
```
$ git clone https://github.com/scisoft/autocmake.git
```
I mean without disabling the SSL verification.

**Comment by miroi** [comment]
The cloning works without problem (see below), only testing does not work.

Some ssh-connection issue, I will ask admin.
~~~
ilias@147.213.242.7:~/work/programming/autocmake_devel/.git clone https://github.com/scisoft/autocmake.git
Cloning into 'autocmake'...
remote: Counting objects: 750, done.
remote: Total 750 (delta 0), reused 0 (delta 0), pack-reused 750
Receiving objects: 100% (750/750), 112.33 KiB, done.
Resolving deltas: 100% (439/439), done.
ilias@147.213.242.7:~/work/programming/autocmake_devel/.cd autocmake/
ilias@147.213.242.7:~/work/programming/autocmake_devel/autocmake/.ls
AUTHORS.md  LICENSE  README.md  appveyor.yml  compilers/  doc/  example/  lib/  modules/  test/  update.py*
ilias@147.213.242.7:~/work/programming/autocmake_devel/autocmake/.py.test -vv test/test.py 
========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.9 -- py-1.4.30 -- pytest-2.7.2 -- /gpfs/home/utils/LINUX/python-2.7.9/bin/python
rootdir: /gpfs/home/ilias/work/programming/autocmake_devel/autocmake/test, inifile: 
collected 4 items 

test/test.py::test_cxx FAILED
test/test.py::test_cxx_auto FAILED
test/test.py::test_fc FAILED
test/test.py::test_fc_blas FAILED
.
.
>           self._sslobj.do_handshake()
E           IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py:788: IOError
======================================================== 4 failed in 3.41 seconds ========================================================
~~~

**Comment by bast** [comment]
Try this in your python console:
```python
import urllib
opener = urllib.URLopener()
opener.retrieve('https://raw.githubusercontent.com/scisoft/autocmake/master/test/test.py', '/tmp/testing-urllib')
```

I guess this does not work on that machine due to some outdated CA certs.

**Comment by miroi** [comment]
Yes, outdated certificate on that machine; the full output is below.

I will wait for fix by admin, and then I shall close this 'simple' issue.
~~~
ilias@147.213.242.7:~/work/programming/autocmake_devel/autocmake/.python
Python 2.7.9 (default, Jul 20 2015, 15:02:15) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib 
>>> opener = urllib.URLopener()
>>> opener.retrieve('https://raw.githubusercontent.com/scisoft/autocmake/master/test/test.py', '/tmp/testing-urllib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/gpfs/home/utils/LINUX/python-2.7.9/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
>>> 
~~~

**Comment by bast** [comment]
Thanks Miro - good to know. I will close the issue right away since it is not really an Autocmake problem.

**Comment by miroi** [comment]
Well,
 how about Python3 ? At this machine (IBM Linux Zilina) this works:
~~~
ilias@147.213.242.7:~/.python3
Python 3.4.2 (default, Jul 27 2015, 14:47:23) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.request
>>> urllib.request.urlretrieve('https://raw.githubusercontent.com/scisoft/autocmake/master/test/test.py')
('/tmp/tmpzenzkk38', <http.client.HTTPMessage object at 0xfff9b03f710>)
>>> 
~~~

But the testing fails (other reasons). Is autocmake adapted for Python3 ?

~~~
ilias@147.213.242.7:~/work/qch/software/autocmake/.py.test -v test/test.py 
========================================================== test session starts ===========================================================
platform linux -- Python 3.4.2 -- py-1.4.30 -- pytest-2.7.2 -- /gpfs/home/utils/LINUX/python-3.4.2/bin/python3.4
rootdir: /gpfs/home/ilias/work/qch/software/autocmake/test, inifile: 
collected 4 items 

test/test.py::test_cxx FAILED
test/test.py::test_cxx_auto FAILED
test/test.py::test_fc FAILED
test/test.py::test_fc_blas FAILED

================================================================ FAILURES ================================================================
________________________________________________________________ test_cxx ________________________________________________________________

    def test_cxx():
>       stdout, stderr = configure_build_and_exe('cxx', 'python setup.py --cxx=g++')

../test.py:111: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'cxx', setup_command = 'python setup.py --cxx=g++ build-2015-07-27-16-03-09'

    def configure_build_and_exe(name, setup_command):
    
        stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
    
        os.chdir(os.path.join(HERE, name, 'cmake'))
        shutil.copy(os.path.join('..', '..', '..', 'update.py'), 'update.py')
        if not os.path.exists('lib'):
            os.makedirs('lib')
        shutil.copy(os.path.join('..', '..', '..', 'lib', 'config.py'), 'lib')
        fetch_url(src='https://github.com/docopt/docopt/raw/master/docopt.py',
                  dst='lib/docopt.py')
        stdout, stderr = exe('python update.py ..')
        os.chdir(os.path.join(HERE, name))
    
        if sys.platform == 'win32':
            setup_command += ' --generator="MinGW Makefiles"'
    
        setup_command += ' build-%s' % stamp
    
        stdout, stderr = exe(setup_command)
    
>       os.chdir(os.path.join(HERE, name, 'build-%s' % stamp))
E       FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/ilias/work/qch/software/autocmake/test/cxx/build-2015-07-27-16-03-09'

../test.py:96: FileNotFoundError
---------------------------------------------------------- Captured stderr call ----------------------------------------------------------
Traceback (most recent call last):
  File "update.py", line 5, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name OrderedDict
python: can't open file 'setup.py': [Errno 2] No such file or directory
_____________________________________________________________ test_cxx_auto ______________________________________________________________

    def test_cxx_auto():
>       stdout, stderr = configure_build_and_exe('cxx_auto', 'python setup.py --cxx=g++')

../test.py:118: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'cxx_auto', setup_command = 'python setup.py --cxx=g++ build-2015-07-27-16-03-09'

    def configure_build_and_exe(name, setup_command):
    
        stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
    
        os.chdir(os.path.join(HERE, name, 'cmake'))
        shutil.copy(os.path.join('..', '..', '..', 'update.py'), 'update.py')
        if not os.path.exists('lib'):
            os.makedirs('lib')
        shutil.copy(os.path.join('..', '..', '..', 'lib', 'config.py'), 'lib')
        fetch_url(src='https://github.com/docopt/docopt/raw/master/docopt.py',
                  dst='lib/docopt.py')
        stdout, stderr = exe('python update.py ..')
        os.chdir(os.path.join(HERE, name))
    
        if sys.platform == 'win32':
            setup_command += ' --generator="MinGW Makefiles"'
    
        setup_command += ' build-%s' % stamp
    
        stdout, stderr = exe(setup_command)
    
>       os.chdir(os.path.join(HERE, name, 'build-%s' % stamp))
E       FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/ilias/work/qch/software/autocmake/test/cxx_auto/build-2015-07-27-16-03-09'

../test.py:96: FileNotFoundError
---------------------------------------------------------- Captured stderr call ----------------------------------------------------------
Traceback (most recent call last):
  File "update.py", line 5, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name OrderedDict
python: can't open file 'setup.py': [Errno 2] No such file or directory
________________________________________________________________ test_fc _________________________________________________________________

    def test_fc():
>       stdout, stderr = configure_build_and_exe('fc', 'python setup.py --fc=gfortran')

../test.py:125: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'fc', setup_command = 'python setup.py --fc=gfortran build-2015-07-27-16-03-10'

    def configure_build_and_exe(name, setup_command):
    
        stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
    
        os.chdir(os.path.join(HERE, name, 'cmake'))
        shutil.copy(os.path.join('..', '..', '..', 'update.py'), 'update.py')
        if not os.path.exists('lib'):
            os.makedirs('lib')
        shutil.copy(os.path.join('..', '..', '..', 'lib', 'config.py'), 'lib')
        fetch_url(src='https://github.com/docopt/docopt/raw/master/docopt.py',
                  dst='lib/docopt.py')
        stdout, stderr = exe('python update.py ..')
        os.chdir(os.path.join(HERE, name))
    
        if sys.platform == 'win32':
            setup_command += ' --generator="MinGW Makefiles"'
    
        setup_command += ' build-%s' % stamp
    
        stdout, stderr = exe(setup_command)
    
>       os.chdir(os.path.join(HERE, name, 'build-%s' % stamp))
E       FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/ilias/work/qch/software/autocmake/test/fc/build-2015-07-27-16-03-10'

../test.py:96: FileNotFoundError
---------------------------------------------------------- Captured stderr call ----------------------------------------------------------
Traceback (most recent call last):
  File "update.py", line 5, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name OrderedDict
python: can't open file 'setup.py': [Errno 2] No such file or directory
______________________________________________________________ test_fc_blas ______________________________________________________________

    def test_fc_blas():
        if sys.platform != 'win32':
>           stdout, stderr = configure_build_and_exe('fc_blas', 'python setup.py --fc=gfortran --blas=auto')

../test.py:133: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'fc_blas', setup_command = 'python setup.py --fc=gfortran --blas=auto build-2015-07-27-16-03-11'

    def configure_build_and_exe(name, setup_command):
    
        stamp = datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d-%H-%M-%S')
    
        os.chdir(os.path.join(HERE, name, 'cmake'))
        shutil.copy(os.path.join('..', '..', '..', 'update.py'), 'update.py')
        if not os.path.exists('lib'):
            os.makedirs('lib')
        shutil.copy(os.path.join('..', '..', '..', 'lib', 'config.py'), 'lib')
        fetch_url(src='https://github.com/docopt/docopt/raw/master/docopt.py',
                  dst='lib/docopt.py')
        stdout, stderr = exe('python update.py ..')
        os.chdir(os.path.join(HERE, name))
    
        if sys.platform == 'win32':
            setup_command += ' --generator="MinGW Makefiles"'
    
        setup_command += ' build-%s' % stamp
    
        stdout, stderr = exe(setup_command)
    
>       os.chdir(os.path.join(HERE, name, 'build-%s' % stamp))
E       FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/home/ilias/work/qch/software/autocmake/test/fc_blas/build-2015-07-27-16-03-11'

../test.py:96: FileNotFoundError
---------------------------------------------------------- Captured stderr call ----------------------------------------------------------
Traceback (most recent call last):
  File "update.py", line 5, in <module>
    from collections import OrderedDict, namedtuple
ImportError: cannot import name OrderedDict
python: can't open file 'setup.py': [Errno 2] No such file or directory
======================================================== 4 failed in 3.24 seconds ========================================================
~~~

**Comment by bast** [comment]
In principle Autocmake should work with Python 3. At least this is the aim.
On that machine you need to investigate why this fails (in a console):
```python
from collections import OrderedDict
```

**Comment by miroi** [comment]
Hi,
with proper Python module loaded,
~~~
lias@147.213.242.7:~/work/qch/software/autocmake/test/.module list
Currently Loaded Modulefiles:
  1) ibm/xlf-14.1   2) ibm/vac-12.1   3) python-3.4.2
~~~

the problem is (update.py  #!/usr/bin/env python) that the default python is pointing to 2.6  - 
~~~
ilias@147.213.242.7:~/work/qch/software/autocmake/test/.python
Python 2.6.8 (unknown, May 29 2012, 22:57:55) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import OrderedDict, namedtuple
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name OrderedDict
>>> 
~~~
while Python3 works fine (has to be called as python3):
~~~
ilias@147.213.242.7:~/work/qch/software/autocmake/test/.python3
Python 3.4.2 (default, Jul 27 2015, 14:47:23) 
[GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> from collections import OrderedDict
>>> from collections import OrderedDict, namedtuple
>>>   
~~~
Something for the IBM Linux admin.
